print("hello world")
print('kritika')
print('i am "more"happy')
print('i am "more"happy')
print("first line\tSecond line")
print("this is beautiful /\\/\\/\\ mountain")
print("hello worlds")
print('i\'m kritika ')
print("\'")
print("\"")
print("\\")
print("this\nis\nkritika")
print("sita\tgita")
print("i am kritika\ba")
print(123)
print("\\\' - \'")
print("\\\\\' - \\")
print("\\\\\\\' - \\\'")
print("This is \\\\ double backslash")
print("This is /\\/\\/\\/\\/\\ mountain")